# Generated by Django 4.0.2 on 2023-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_form_creator_ip_alter_clientip_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='creator_ip',
            field=models.CharField(max_length=30),
        ),
    ]
