# Generated by Django 4.0.2 on 2023-04-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_form_creator_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientip',
            name='client_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ip', to='index.form'),
        ),
    ]
