# Generated by Django 4.2.1 on 2023-08-31 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0008_formsubmission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormSubmission",
        ),
    ]
